# Generated by Django 3.1.1 on 2021-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('life_time_km', models.IntegerField(default=0)),
                ('life_time_floors', models.IntegerField(default=0)),
            ],
        ),
    ]
