# Generated by Django 3.1.1 on 2021-02-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbitdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='life_time_floors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='life_time_km',
        ),
    ]
