# Generated by Django 3.1.1 on 2021-02-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbitdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='life_time_floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='life_time_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbadges',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitbitdata.user'),
        ),
    ]
